#!/bin/bash

# 乘法口诀表

for (( i=1;i<=9;i++ ))
do
	str=$''
	for (( j=1;j<=9;j++ ))
	do
		str=${str}$i*$j=`echo $i*$j | bc`$' '
	done
	echo $str	
done


# 第二个版本

for (( i=1;i<=9;i++ ))
do
	str=''
	for (( j=1;j<=$i;j++ ))
	do
		str=${str}$i*$j=$[ $i*$j ]$' '
	done
	echo $str
done > cfkjb.log
