#!/usr/bin/php
<?php

$arr = array(0,1,2,3,4,5,6);

$st = microtime(true);
$n = 1000;
for($i=0;$i<$n;$i++){
	array_key_exists($i,$arr);
}
echo 'array_key_exists:'.(microtime(true)-$st);
echo PHP_EOL;


$t1 = microtime(true);
for($i=0;$i<$n;$i++){
	isset($arr[$i]);
}

echo 'isset:'.(microtime(true)-$t1);
echo PHP_EOL;

